tap "getantibody/tap"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

cask "minikube"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "font-fira-code"

brew "ansible"
brew "antibody"
brew "awscli"
brew "exa"
brew "fd"
brew "git"
brew "go"
brew "hugo"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "nano"
brew "neofetch"
brew "protobuf"
brew "ripgrep"
brew "watch"
brew "wifi-password"
brew "xz"
brew "zsh"
